### ISSUE TITLE
Run the JVM in a WebWorker

### ISSUE THREAD

**Issue by jvilk** [plasma-umass/doppio#127]
Doppio currently runs in the main JavaScript thread, which causes the browser to be less responsive than desired. While we could "fix" this by yielding the thread more often, this comes with a speed penalty.

For browsers that support it, we should run the JVM in a WebWorker. Note that we are not mapping threads to WebWorkers -- simulating shared memory would be too slow / cumbersome / difficult -- we are mapping JVM instantiations to WebWorkers.

The main JavaScript thread would be responsible for checking for and handling messages sent from the WebWorker for various events, such as:
* Printing to the console.
* Requesting a prompt for input.
* Requesting a file from `localStorage`.
* Saving a file to `localStorage`.
* Any other future events that require access to the DOM (e.g. Doppio classes that allow for webpage manipulation).

For browsers that do not support WebWorkers (e.g. IE before 10), we can just simulate WebWorkers in the main JavaScript thread. To improve those web browsers' responsiveness, we could just yield the JavaScript thread after a certain duration of time (easy enough to do in the interpreter).

This should not impact the Node JS frontend. It will just impact how the browser frontend runs the JVM, how the node emulation requests `localStorage` files, how printing to/receiving input from the console works, and any other browser-specific features that we add to Doppio in the future.

**Comment by bertung** [comment]
What is the status of "in web worker" runtime? can we now run doppio solely from a web worker. We do not need the front end part? Probably a separate question but, is it possible to preload java.lang, java.util, and java.io packages?

**Comment by bpowers** [comment]
I'm not sure right now, but I'll be looking at this in the next few weeks

**Comment by jvilk** [comment]
I have no reason to believe why this would not work. This issue refers to exposing a concise API for invoking DoppioJVM in a WebWorker (e.g. `new Doppio({webworker: true})`). Right now, DoppioJVM *should* work in a WebWorker, but there's no plug-and-play API to make it simple.

**Comment by bertung** [comment]
I think there is no need for an extra API. Just a simple postMessage/onmessage communication protocol would be enough to invoke DoppioVM. A front end API should not be a focal point of DoppioVM. Let the developers find their own way on that front.

**Comment by jvilk** [comment]
DoppioJVM works just fine in a webworker; I didn't even need to change anything. I just made a commit that switched to using WWs for testing, so I'm closing this out.

The only issue currently is a (throughput-based) performance regression in a WebWorker compared with the main thread, which I'm actively investigating.

**Comment by bertung** [comment]
We can run DoppioVM only in a web worker because the main thread is already busy with tons of other stuff. Could you open another issue for the performance regression so that we can follow the imrpovements on that? just a thought :).

**Comment by jvilk** [comment]
Sure, I'll do that. I'd also appreciate stars on this Chrome issue, which seems to be the culprit in Chrome:

https://code.google.com/p/chromium/issues/detail?id=344814&can=5&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified

I haven't checked to see if performance differs in other browsers yet.
