### ISSUE TITLE
Change folder structure in in-browser demo

### ISSUE THREAD

**Issue by jvilk** [plasma-umass/doppio#142]
Currently, we shove all of our files into `/home/doppio`, which presents the demo user with a cluttered home directory. It also complicates the filesystem logic, since we have multiple file sources mapped in there (the webserver, `localStorage`, preloaded classes...).

We have hacked around all of these things (e.g. `file.temp` for preloaded files, `f.mod` to track modified files), but I believe it's time for a change.

We should have the webserver files mapped into a read-only directory at the root level (`/sys`?). Anything from there that we want in the home directory can be symlinked in (yes, we should have symlink support).

The root file system will be mapped to `localStorage`, with any other filesources "mounted" into it.

Overall, I believe the filesystem logic will be simpler, more performant (no complex weird composed file sources), and will have more features (symlinking! mounting! easy expansion into cloud storage, perhaps!).

This should probably be done in conjunction with #140, which will end up being a rewrite.

**Comment by perimosocordiae** [comment]
This should be handled by doppio-demo now. Closing.
