### ISSUE TITLE
Replace terminal on demo page

### ISSUE THREAD

**Issue by jvilk** [plasma-umass/doppio#143]
Our web terminal has been a regular source of issues for us.

We have had to suffer through the following things:
* Compatibility hacks for browsers. Apparently input doesn't work in Windows Phone 8's IE browser now, too...
* API hacks. Just handling the simple case of returning from an operation has caused a number of bugs.
* The terminal does not appear to be maintained anymore.

I remember looking for a web-terminal a year ago and not finding plenty of half-baked solutions but nothing decent. I recently stumbled upon this link, which looks promising:

http://www.masswerk.at/termlib/

I haven't investigated compatibility yet.

**Comment by perimosocordiae** [comment]
This should be handled by doppio-demo now. Closing.
