### ISSUE TITLE
Update Demo

### ISSUE THREAD

**Issue by jvilk** [plasma-umass/doppio#279]
Our demo is old. We need a new one.

Things we should do before launching a new demo:
* [x] Use almond to expose a `doppio` global that corresponds to the JVM class.
* [ ] Decouple demo code from the repository (make [doppio-demo](https://github.com/perimosocordiae/doppio-demo) use doppio.js as a e.g. bower dependency).
  * Allows us to bundle many more apps into the demo without bloating/complicating this repository.
* [x] Run benchmarks as a sanity check on old demo and new demo to check for potential regressions.

Things we might want to consider before launching a new demo:
* [x] Using BrowserFS's zip file functionality for `java -jar` in the browser. (#71)
* [x] Unifying option parsing for `runner.js` and the `java` command in the browser using `option_parser`.
  * Could just make a function on the JVM object that accepts a `java` command.
* [x] Dramatically simplify the browser interface integrated into the repository for testing.
  * Not really needed and can be backburnered.

**Comment by jvilk** [comment]
We did it! 🎉

**Comment by perimosocordiae** [comment]
Is it just me, or is the performance _really_ slow? Running the Fib demo takes a few seconds to print anything, each time you run it. (Chrome/Windows 10)

I know that we're no longer using the caching/JVM-reuse hacks from the bad old days, but is that expected behavior?

**Comment by jvilk** [comment]
Yes. We took a performance hit after increasing compatibility and, most notably, when we stopped loading user programs in the bootstrap classloader and instead used the app classloader as-intended.
