### ISSUE TITLE
Upgrade VM to Java SE 8

### ISSUE THREAD

**Issue by jvilk** [plasma-umass/doppio#299]
Not a priority at this instant, but should eventually be done; Java 6 is no longer officially supported by Oracle, and there's some Java 8 momentum now that the language has some long-missing features.

Use this bug to track all bugs related to moving the VM to Java 7 or 8.

Links:
* [JVM Spec page](http://docs.oracle.com/javase/specs/)
  * [Spec for 7](http://docs.oracle.com/javase/specs/jvms/se7/html/index.html)
  * [Spec for 8](http://docs.oracle.com/javase/specs/jvms/se8/html/index.html)
* [PDF diff between SE 7 and SE 8](http://docs.oracle.com/javase/specs/jvms/se8/jvms8-diffs.pdf) (Awesome that Oracle *officially* provides this) (If you're confused upon opening it, the first change appears in Chapter 4, on page 86 of the PDF / 72 of the document)

**Comment by perimosocordiae** [comment]
Merged! Closing!
