### ISSUE TITLE
grunt build fails (grunt cannot symlink on windows?)

### ISSUE THREAD

**Issue by wizzard0** [plasma-umass/doppio#316]
Running "make_build_dir:default" (make_build_dir) task
>> Created build folder: C:\dev\doppio\build\dev-cli
Fatal error: Cannot symlink classes to build\dev-cli\classes: Error: EPERM, operation not permitted 'C:\dev\doppio\build\dev-cli\classes'

at 927371e330b3a759b4eb7157df6102fc38df2ff3, windows 8.1 x64

**Comment by jvilk** [comment]
As of the commit I just made, we now copy when symlinking fails.
