### ISSUE TITLE
Compile + optimize instead of interpret

### ISSUE THREAD

**Issue by int3** [plasma-umass/doppio#32]
General idea:

* Replace opcodes with expression 'templates'. So `iadd` will be defined like this: `in: [1,1], out: [1], exp: '$0 + $1'`, which means that it takes two 1-byte values from the stack and pushes a one-byte value. We can re-generate our current set of `execute` functions from these templates, but we could also string multiple opcodes together into one larger function.

* When compiling, we can evaluate the stack symbolically. So when `iadd` is called we might have symbols (strings) 'a' and 'b' on the stack, and when we are done we have the string 'c' on the stack. We can then produce code like `c = a + b`. Not absolutely clear on how to analyze jumps and exception handling at the moment. See [Harissa][1] for more details.

* Reduce virtual method lookup overhead by having compiled classes contain references to inherited functions.

* Reconstruct 'normal' control flow code via decompilation. See Harissa, or [Emscripten][2].

[1]: http://static.usenix.org/publications/library/proceedings/coots97/full_papers/muller/muller_html/node3.html#SECTION00030000000000000000
[2]: https://github.com/kripken/emscripten/blob/master/docs/paper.pdf

**Comment by jvilk** [comment]
With #443 merged, we now have a basic JIT!

**Comment by perimosocordiae** [comment]
:tada:
