### ISSUE TITLE
Use karma for browser unit tests

### ISSUE THREAD

**Issue by jvilk** [plasma-umass/doppio#329]
Rather than use our demo interface to *manually* run unit tests in each browser, we can use Karma to launch multiple browsers and run unit tests in a single grunt command.

All we need to do is write an adapter from our unit tests to an existing JavaScript unit test framework (e.g. Jasmine), and then Karma does the rest.

Once we do this, we can separate our demo code from the Doppio repository!

**Comment by perimosocordiae** [comment]
This isn't working for me, yet. It runs all the tests in the browser, but hangs afterward. Also, it reports that 29/64 tests failed, but doesn't show the diffs for any of them (unless I view the console in the karma window).

**Comment by jvilk** [comment]
All output should be in the console window. The browser(s) configured in the gruntfile launch in the background, letting you nest the console window underneath your text editor and watch test results live as they happen.

**Comment by jvilk** [comment]
You can see the desired workflow in this screencast (I've linked to the appropriate time):

https://www.youtube.com/watch?v=MVw8N3hTfCI#t=228

**Comment by perimosocordiae** [comment]
Fair enough, though I don't think our use-case works very well with the test-on-save workflow: the full test suite takes about 1 minute and 30 seconds to run, and that's after re-building doppio. Also, I tried editing a file after running the test suite, and karma didn't do anything on save.

Also, only one diff ever appears in the console output, even though many tests fail: http://pastebin.com/zpsbrge0

**Comment by jvilk** [comment]
Yeah, I think there's some weird stuff going on that I'll need to check.

> Fair enough, though I don't think our use-case works very well with the test-on-save workflow: the full test suite takes about 1 minute and 30 seconds to run, and that's after re-building doppio. 

Agreed. It will get better when Doppio can run in a WebWorker.

**Comment by perimosocordiae** [comment]
Whatever changed, it seemed to fix things. The karma tests now pass 62/64 tests, only failing the FileOps test (fails check that `/tmp` is writeable) and the CatchingClinitException test (not sure why).
