### ISSUE TITLE
Switch over to TypeScript Internal Modules

### ISSUE THREAD

**Issue by jvilk** [plasma-umass/doppio#350]
I've been mulling this over for awhile. Switching over to TypeScript internal modules would:

* Fix source maps because we no longer have ad-hoc concatted RequireJS boilerplate*
* Remove our dependency on RequireJS/Almond.
  * Smaller library size.
* Produce *.d.ts files that actually function and can be included in the distributable.
  * This is important for being able to decouple our demo and still have working type annotations.
* Exposes all of our functionality under a single global namespace.
* Makes circular dependencies possible, since we can specify the correct initialization order.
* Let us produce a single `doppio.js` for Node, browser, *and* RequireJS.
  * Potential downside: Node releases would need to be packaged as one file, since we will no longer be using its module system. I personally view this as an upside.

Downsides:
* In some cases, we would need to specify an ordering on the files. TypeScript uses some heuristic to figure out ordering, but I think it's not great in all cases. A lot of projects have a master 'include' file that specifies the exact ordering (think: master C header file), and have all of their modules reference this file so they have type annotations for every module.

\* We'd need to update ice-cream, though, to output sourcemaps.

**Comment by perimosocordiae** [comment]
ping @int3 for https://github.com/int3/ice-cream update

**Comment by jvilk** [comment]
I messed around a bit with internal modules on Ninia, and discovered some things.

> Makes circular dependencies possible, since we can specify the correct initialization order.

Only somewhat correct. You still cannot `import` things such that you have a circular dependency. However, you can do e.g. `Doppio.JVM.Thread` to reference `Thread` from the global object without importing it, which is fine for code not on the critical path.

**Comment by jvilk** [comment]
You can't mix internal modules and Node modules, which means we wouldn't be able to rely on the Node ecosystem like we do now. Thus, I am closing this issue.
