### ISSUE TITLE
Wiki typo 

### ISSUE THREAD

**Issue by guizos** [plasma-umass/doppio#355]
When trying to plugin Doppio into a frontend (https://github.com/plasma-umass/doppio/wiki/Doppio-Developer-Guide)

The guide specifies the path ./vendor/classes for the Java Class Library, but the path does not exists in the doppio release folder. Instead, there is a ./classes folder. but I think that's the folder where Javac and other tools are stored. Where is the ./vendor/classes folder? ./vendor/java_home/classes?

By the way, I don't know if this is the best way to highlight this. Sorry in case I'm not raising this issue properly.

**Comment by jvilk** [comment]
Nope, you can file issues here, or email our mailing list. Either way works.

We recently-ish moved `classes` to `java_home` as you suspect to keep everything in that one folder. I just updated the wiki to reflect this change. Let me know if you find other issues, or have other problems/questions!

Also, you may notice that there's no frontend code in our repository. We removed it, and I'm in the process of migrating it to a demo repository. You can see an old version of our demo code [here](https://github.com/plasma-umass/doppio/blob/93d6b06c67792a2b21958f22cb99151268a0a760/browser/frontend.ts).
