### ISSUE TITLE
Documentation related to release and usage

### ISSUE THREAD

**Issue by Naitik333** [plasma-umass/doppio#368]
Hi,

First of all its great idea to execute the java code on browser and call the code using Java script.
I want to test the doppio scripts to run some basic Java code, But i didn't find any downloadable release version or anything like that.
Can i get doppio.js and other required files in zip and some guide on how to integrate in my java script and steps to execute the required class files from the java script?
It will be very useful as i wanna try it first and for that i dont want to download all the softwares and build it from scratch.
Waiting for prompt answer.

**Comment by perimosocordiae** [comment]
There is a relatively up-to-date version of doppio.js at [the doppio-demo repository](https://github.com/jvilk/doppio-demo/tree/master/vendor/doppio/dist). I would recommend downloading that whole repository and modifying from there to get started.

Eventually, we will have official releases and this process will be much easier.

**Comment by jvilk** [comment]
Yes, what @perimosocordiae said. I'm unfortunately tied up with other projects at the moment, but I'm planning on coming back with a vengeance sometime next week. I encourage you to check out the doppio-demo repository until I get the chance to write a how-to guide.

**Comment by Naitik333** [comment]
Thanks for prompt reply.
Do we only need doppio.js or any other files as well? 
Some basic guide on using doppio.js will be very appreciated.

**Comment by Naitik333** [comment]
Hi,

I was able to run doppio from my js file :)
I have some doubts regarding it -
1. How does doppio works? Does it download all the native files to client browser and execute it in browser it self? If so what is the size of downloaded files?
2. we can use Java_cli.java to execute the particular class or jar files main method. Is there any provision to execute particular method of the class?
3. we can get all the outputs in processor.st.out methods. but it will contain all the logging that happens. Suppose i want to execute particular method and it returns Integer value and i want to manipulate the returned value in my javascript. Can I do that?

Thanks. Waiting for answers

**Comment by jvilk** [comment]
@Naitik333 I'm working on fixing a few lingering bugs in the `new-objects` branch before doing a new release w/ updated documentation.

Some quick answers:

1. Doppio downloads and executes *.class files, yes. The size of the JRE as a whole is ~30MB compressed. The demo at `doppiojvm.org` downloads the class files individually, but the current version in `doppio-demo` uses JAR files directly. I might update the demo code to preload and extract it into browser storage to improve performance.

2. At the moment, if you want to execute a particular method in a class, you want to create a `main` function in a new Java class that executes it. It's the same as if you execute Java on the command line; it will run your `main` function first. If you want to interoperate with the program once it's running, you'll need to experiment with native methods. I eventually want to make this use case easier.

3. You can write a Java program that calls `classes,doppio.JavaScript.eval()`, which will evaluate an arbitrary string as JavaScript (e.g. `classes.doppio.JavaScript.eval("jsFunction('Return value is " + Dog.getFoo()');"`).

Make sense?

**Comment by jvilk** [comment]
We now have a [simple example program](https://github.com/plasma-umass/doppio/blob/master/docs/examples/simple.html) in the repository that you can build in a single `grunt` command to get people started. The [doppio-demo](https://github.com/plasma-umass/doppio-demo) is a more complex application that can also be built easily.
