### ISSUE TITLE
Cannot find module './build/Release/shell' due to execSync dependency in doppio

### ISSUE THREAD

**Issue by jimfb** [plasma-umass/doppio#380]
Running "grunt build" will sometimes result in:
```
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module './build/Release/shell'
Warning: Task "build" not found. Use --force to continue.

Aborted due to warnings.
```

I believe the error is related to execSync which is a dependency of this project.  The version that gets installed apparently doesn't build on some versions of npm/node.  Root cause appears to be related to https://github.com/mgutz/execSync/issues/27 though I do have python 2.7.

My solution was to use `nvm` to change node versions.  I don't remember which version I landed on that worked, but I do know that v0.10.33 was failing on my macbook.

Related to https://github.com/jvilk/doppio-demo/issues/13, though I think the version constraints here are slightly different.

I'm posting this issue here mostly so that when someone does a google/github/doppio search for the error, they will find this and my notes will be helpful in some way, but it's worth tracking the issue and trying to expand the acceptable dependency version range (particularly in the up direction).

**Comment by jvilk** [comment]
The `new-objects` branch doesn't depend on `execSync`, and will soon replace master.

https://github.com/plasma-umass/doppio/pull/378

I'm hoping to merge that in over the next week.

**Comment by jimfb** [comment]
Great, thanks!  Super fast response, much appreciated!  And BTW, spectacular work on this project!

**Comment by jvilk** [comment]
Aww, shucks. Thanks! There's a lot in the pipeline, too (especially regarding *speed*). I hope that this next version of doppio doesn't bitrot as much as the `master` branch has over the past year; I've been working on it for awhile.

**Comment by jvilk** [comment]
`new-objects` is now in master, and no longer depends on execSync.
