### ISSUE TITLE
Doppio Developer Guide issues

### ISSUE THREAD

**Issue by akadeev** [plasma-umass/doppio#384]
Hello,
I want to reproduce Doppio Developer Guide instruction on how to call my own natives with doppio and have some issues. My code is in the akadeev/java-js-sample repository. 

I am doing these steps:
  javac classes/util/Test.java
  ../../doppio/doppioh -classpath . -d natives classes/util/Test
  edit appeared native js
  ../../doppio/doppio -Xnative-classpath natives classes/util/Test

And getting:
  Exception in thread "main" java.lang.UnsatisfiedLinkError: Native method 'classes.util.Test.addTwo(I)I' not implemented.

Can you explain me what am I doing wrong with this sample? I have tried many configurations, master and new-objects branches and nothing worked.

**Comment by jvilk** [comment]
Ah! I'm so sorry. I just noticed that `src/java_cli.ts` *never processes the `native-classpath` argument*. Whoops!

I just pushed a fix to `new_objects`, and verified that it works with your code. Can you let me know if that works for you? (Make sure you run `npm install` again before building -- there are some updated dependencies.)

Feel free to open further issues if you have any other troubles!

**Comment by akadeev** [comment]
Thank you, it works perfectly now!
