### ISSUE TITLE
Can't type cast to long (in native method)

### ISSUE THREAD

**Issue by hrj** [plasma-umass/doppio#394]
Test-case:

### test.js

```js
registerNatives({
  'test': {
    // This works
    'getInteger()I': function(thread) {
      return 0;
    },

    // This doesn't work
    'getLong()J': function(thread) {
      return 0;
    },
  }
});
```

### test.java
```java
class test {
  public static void main(String[] args) {
    final int ansI = getInteger();
    System.out.println("Int ans: " + ansI);

    final long ansL = getLong();
    System.out.println("Long ans: " + ansL);
  }

  public static native int getInteger();
  public static native long getLong();
}
```

### Result

Running with `doppio` gives:

```
Int ans: 0
Encountered error: TypeError: pop2(...).compare is not a function
TypeError: pop2(...).compare is not a function
    at Array.a.lcmp (../../../src/opcodes.ts:917:28)
    at a.run (../../../src/threading.ts:129:19)
    at a.run (../../../src/threading.ts:614:33)
    at Immediate._onImmediate (../../../src/threadpool.ts:83:16)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Interestingly, running with `doppio-dev` gives a different stack trace:

```
Int ans: 0
Encountered error: TypeError: rv1.lessThanOrEqual is not a function
TypeError: rv1.lessThanOrEqual is not a function
    at validateReturnValue (../../../src/threading.ts:1046:30)
    at JVMThread.asyncReturn (../../../src/threading.ts:846:14)
    at NativeStackFrame.run (../../../src/threading.ts:304:18)
    at JVMThread.run (../../../src/threading.ts:611:35)
    at Immediate._onImmediate (../../../src/threadpool.ts:83:16)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by perimosocordiae** [comment]
This behavior is expected, though we've probably failed to document it very well. We use the `gLong.js` library to provide support for true 64-bit long integers (as JS numbers can only be trusted up to 53 bits).

When working with longs in a native function, doppio expects them to be gLong objects, hence the call to `.lessThanOrEqual` in your `doppio-dev` trace.

**Comment by perimosocordiae** [comment]
To demonstrate this, try writing a native function like this:
```javascript
    'inspectLong(J)V': function(thread, num) {
      console.log(num);
    },
```

**Comment by hrj** [comment]
@perimosocordiae makes sense, thanks!

Is it possible for this to be handled automatically, by the code which is doing the type coercion?

Otherwise, I will modify my code to convert to gLong manually.

**Comment by perimosocordiae** [comment]
It's possible to add logic [here](https://github.com/plasma-umass/doppio/blob/06cdb7cd72ae376591f263c8bfc710fe6b101cbc/src/threading.ts#L301) in which the `'J'` case checks if `rv` is already a gLong and does a conversion if it isn't.

There are two main reasons why we haven't done that already:
 * forcing native methods to be explicit about returning gLong objects helps us discover bugs in our implementation of the stdlib natives
 * adding a conditional to every long return seems like it would be a noticeable performance hit (though I haven't actually tested)

Of course, there could be better reasons for adding the auto-conversion logic. @jvilk, what do you think?

**Comment by jvilk** [comment]
Mainly, **I want to limit the amount of magic in the platform.** If you intentionally decide to create a native method for DoppioJVM that returns a `long` type, you should know that it's an object, and it's considerably more expensive to operate on than other base types. It would be best to return integers or doubles when possible.

It wouldn't be a performance hit in the synchronous case, I believe, since we already check return types from natives to push the extra `null` on the stack.

Also, you should use `doppio-dev` or `doppio-fast-dev` during development. They contain invaluable assertions that will be thrown when your code does something wrong, like return an incorrect type.

**Comment by jvilk** [comment]
I think we answered the question, so I'm closing this issue. Feel free to reopen if that is not the case!
