### ISSUE TITLE
Using IndexedDB instead of LocalStorage if available

### ISSUE THREAD

**Issue by bertung** [plasma-umass/doppio#398]
Using indexedDB instead of LocalStorage could help store more classes at the client side. IndexedDB can hold as much as 500MB of data or even more on some browsers.

**Comment by jvilk** [comment]
Yup, I'm aware! You can actually mount IndexedDB into a file system for DoppioJVM via [BrowserFS](https://github.com/jvilk/BrowserFS). You can also mount Dropbox, or implement your own backend. This has been possible for quite awhile, so I'm not sure where you heard only localStorage could be used! D:

Should I update the docs to use IDB by default?

**Comment by bertung** [comment]
It is written so in "Notes on Architecture/Library Support" on DoppioVM about page :). Good to hear that it is already supported.

**Comment by bertung** [comment]
I think that page is seriously out dated :)

**Comment by jvilk** [comment]
Whoa, where is that? Is that on the old demo page? If so, that's years outdated.

**Comment by bertung** [comment]
Yup, it even says it is written in CoffeScript :).

**Comment by bertung** [comment]
Let me ask you a quick question from this closed case. How much of java.lang.reflect.* is supported?

**Comment by jvilk** [comment]
It should all work.

**Comment by jvilk** [comment]
To give you some confidence: DoppioJVM can run a whole bunch of language implementations, such as Scala, Nashorn, and Jython, that make extensive use of runtime reflection, invokedynamic, etc. DoppioJVM supports it all, including new Java 8 features such as lambdas. :)

**Comment by bertung** [comment]
Awesome thank you very much.
