### ISSUE TITLE
New npm release?

### ISSUE THREAD

**Issue by hrj** [plasma-umass/doppio#399]
I tried the latest master branch by locally publishing it with `npm pack`. It works really well in our tests and is *fast!*

Can you please publish to npm so that we can use it more easily / standard-ly ?

**Comment by jvilk** [comment]
I want to do a release tomorrow or Monday. The current holdup is documentation. I want to ship some documentation and example code in the repository, so I can maintain it in master without confusing people using the stable release. That is he only holdup.

**Comment by jvilk** [comment]
This is deferred right now due to my current schedule. I still don't want to release until I have a good day to generate some basic docs.

**Comment by jvilk** [comment]
Done!

**Comment by jvilk** [comment]
Also, I'm using the `releases` tab of GitHub now.

We should be able to push out new NPM updates much more frequently.
