### ISSUE TITLE
build stucks slowing down the machine to almost freeze

### ISSUE THREAD

**Issue by bertung** [plasma-umass/doppio#402]
My i7/16Gb machine completely stopped responsing on the "Running "includes:default" (includes) task" phase. I have waited half an hour to complete but it just sits there. I had to cancel the build. Would it be hard for you to put built versions to the github repository?

**Comment by jvilk** [comment]
Are you using Node v0.12? It has a problem with this step.

The `includes` procedure is under-optimized. While I could add it to the repository, I would have to disentangle some implicit dependencies in the build process -- which I really don't have the time to do right now. It would be easier to make `includes` generation faster.

**Comment by bertung** [comment]
Yep, Node v0.12.2.

**Comment by jvilk** [comment]
Node v4 does not have this problem.

**Comment by bertung** [comment]
Ok thanks, I will try node4.

**Comment by jvilk** [comment]
I just made a change that makes the includes procedure significantly faster.
