### ISSUE TITLE
Multiple problems with java.nio.file.Files

### ISSUE THREAD

**Issue by hrj** [plasma-umass/doppio#403]
I can create `Path` instances fine. But trying to do something useful with them from `java.nio.file.Files` has issues:

* `Files.exists(path)` and `Files.createDirectories(path)` fails silently and the JVM exits.
* `Files.write(path, bytes)` fails with an exception:
```
java.io.IOException: Error: ENOENT: No such file or directory., '/path/to/file'
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:80)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at java.nio.file.Files.write(Files.java:3292)
        ....
```

**Comment by jvilk** [comment]
I have not implemented the entirety of this interface, and have been implementing them as I find programs that use them. I will attempt to enhance our test suite to test more of the `nio` natives.

**Comment by hrj** [comment]
Ah, I will try to contribute to the test / natives too.

But shouldn't a missing native throw an exception? Here, it seems to fail silently. Maybe this silence is specific to how I am using doppio, hence the question. doppio version: master branch.

**Comment by perimosocordiae** [comment]
Judging by the stack trace, it looks like java.nio is catching the original
exception (which indicates the missing native) and rethrowing as something
else.

**Comment by jvilk** [comment]
I'll accept PRs for this, btw. Test cases alone are appreciated, and fixes are most appreciated -- but must be accompanied by tests. :)

**Comment by hrj** [comment]
I have added some tests, implemented some natives and also fixed some bugs. Waiting for the existing PRs to land before launching more :) Especially the one that fixes travis build.

**Comment by jvilk** [comment]
Awesome! I eagerly await the PR. :)

**Comment by jvilk** [comment]
Closing for now. It's not thoroughly tested yet, but the infrastructure is there!
