### ISSUE TITLE
Figure out why Travis-CI Nondeterministically Fails

### ISSUE THREAD

**Issue by jvilk** [plasma-umass/doppio#406]
Over the past few months, Travis-CI has reported DoppioJVM's build as 'broken'... but it is not.

Travis-CI seems to fail at the following on a regular basis:

* ~~**Firefox Crashes** (most common): Since we switched to using WebWorkers in unit tests, Firefox seems to crash more in Travis. I do not know why.~~
* ~~**Running `javac`.** The command fails with no useful output. I do not know why.~~
* **Fetching TypeScript includes from GitHub.** GitHub is occasionally unreachable. We should add our includes into the repo to avoid needing to do this during build time.
* **SynchronizeTest fails** (rare): I think there's another race condition in SynchronizeTest that we aren't catching.

```
Failed classes/test/Synchronized: Output does not match native JVM.
Doppio | Java
 Starting bar                                                                       Starting bar
 About to run baz                                                                   About to run baz
                                                                                  > bar interrupted
                                                                                  > bar completed
 Exception in thread "Thread-0" java.lang.InterruptedException: interrupt0 called < 
 	at classes.test.Synchronized$Foo.bar(Synchronized.java:17)                      < 
 	at classes.test.Synchronized$BarRunner.run(Synchronized.java:28)                < 
 	at java.lang.Thread.run(Thread.java:745)                                        < 

```

I have no time to fix this right now, unfortunately.

**Comment by hrj** [comment]
About *javac* failure:

The error I see sometimes is:

```
Locating JDK8 installation...

>> Using JDK8 installation at /usr/lib/jvm/java-7-oracle

>> Java: /usr/lib/jvm/java-7-oracle/bin/java

>> Javap: /usr/lib/jvm/java-7-oracle/bin/javap

>> Javac: /usr/lib/jvm/java-7-oracle/bin/javac

>> Detected Java 1.7.0. Unit tests are not guaranteed to pass on versions of Java < 1.8.

...

javac: invalid source release: 1.8
```

The script detects an old version of java. This seems to happen when download of Oracle JRE fails, as seen in [this build](https://travis-ci.org/UprootStaging/doppio/jobs/100758124).

----
I will now try using openjdk.

**Comment by jvilk** [comment]
Ah, so it's a network failure. That seems to be a common Travis theme.

It looks like you've comprehensively sorted out these issues, so I'll close out this issue.

**Comment by hrj** [comment]
Yeah, it looks stable now, but I haven't really looked at the last two (fetching typescript includes and synch tests).

**Comment by hrj** [comment]
And... the build failed just now, due to typescript fetch fail: 

```
Error: unexpected status code: 503 on: https://raw.github.com/borisyankov/DefinitelyTyped/a9ded5b70ede34486731ef6c2e6865f5e9911fc3/dropboxjs/dropboxjs.d.ts
```

**Comment by hrj** [comment]
According to tsd README: "It is recommended you check-in the definitions you install into your VCS."

Github seems to have a rate-limit for the http requests. We need to either setup an application OAuth token or just checkin the definitions into Git.

**Comment by jvilk** [comment]
@hrj there is an OAuth token (see `.tdsrc`). The problem seems to be Travis's network connection.

**Comment by jvilk** [comment]
I should probably switch to checking in the definitions.

**Comment by jvilk** [comment]
Reopening. Let me know if you want to tackle that one. I'm still overburdened with other stuff for a few weeks.

**Comment by jvilk** [comment]
You'd probably need to do the following:

- [ ] Remove dependency on `tsd`/`grunt-tsd`.
- [ ] Remove Grunt task to run `tsd`.
- [ ] Remove typings from `.gitignore`.
- [ ] Add typings to GitHub.

**Comment by hrj** [comment]
Ok, I will do it right away.
