### ISSUE TITLE
is the `rimraf` dependency required?

### ISSUE THREAD

**Issue by hrj** [plasma-umass/doppio#410]
I couldn't find a use for it in any of the source folders.

**Comment by jvilk** [comment]
It may be a peerDependency, which need to be explicitly included for NPM 3. But I don't know off the top of my head. It may also be something I used before, and stopped using later.

**Comment by jvilk** [comment]
Turns out: No, it's not needed.

**Comment by hrj** [comment]
Turns out: it is needed during installation of JDK :)

`console/download_jdk.ts` requires it.

So you probably will have to revert https://github.com/plasma-umass/doppio/commit/e76ac1fe033e1d43ef69062b16873ad0aa2ad0b1
