### ISSUE TITLE
[Question] Serialization of Objects?

### ISSUE THREAD

**Issue by bertung** [plasma-umass/doppio#413]
* Does URLConnection with Object input/output work?

* Does HttpURLConnection work?

if not,

* Can we serialize Objects and convert them to base64 then post them back to server in JSON and deserialize them in a servlet? Are they going to be corrupted in the process?

**Comment by jvilk** [comment]
> Does URLConnection with Object input/output work?

Yes. Object input/output uses the [JVM's `Serializable` interface](https://docs.oracle.com/javase/7/docs/api/java/io/Serializable.html), which DoppioJVM supports.

> Does HttpURLConnection work?

The existing `HttpURLConnection` will probably not work in the way you'd expect, as it opens a TCP socket. We emulate TCP sockets using Websockify, so those connections won't be able to communicate with a vanilla webserver without wrapping the webserver in Websockify, which will forward Websocket connections to vanilla TCP.

> Can we serialize Objects and convert them to base64 then post them back to server in JSON and deserialize them in a servlet?

Yes, you can serialize them in the same manner using object/input streams, which uses the [`Serializable` interface directly](https://docs.oracle.com/javase/7/docs/api/java/io/Serializable.html).

You could write a native that simply takes in a [JVM object as an bytearray](http://stackoverflow.com/questions/2836646/java-serializable-object-to-byte-array) and send the `ArrayBuffer` directly to the server, avoiding base64 encoding altogether:

```
// Native sendBytesToServer([B)V
function sendBytesToServer(thread, byteArr)  {
  // In browsers w/ typed array support, byteArr.array will be a Uint8Array.
  var uint8arr = byteArr.array;
  // Now just send that Uint8Array to the server using XHR
}
```

Hope that helps!

**Comment by bertung** [comment]
Great, thanks for the quick response. Let me clear one thing though, if HttpURLConnection requires websockify, so does URLConnection. Right?

**Comment by jvilk** [comment]
No. `URLConnection` is an abstract class. You can have a `URLConnection` implementation that writes to / reads from a file on the file system (e.g. `JarURLConnection`).

**Comment by bertung** [comment]
Oopps, it is abstract indeed. thanks for the heads up.

**Comment by jvilk** [comment]
Marking as closed. Feel free to reopen if you have additional questions!
