### ISSUE TITLE
[Question] Running more than one application

### ISSUE THREAD

**Issue by bertung** [plasma-umass/doppio#414]
If we have more than one application in /App1, /App2, /App3....../Appn. Is it possible to set a common javaHomePath for all? I see that the javaHomePath is read from this mounted point?

 mfs.mount('/sys', new BrowserFS.FileSystem.XmlHttpRequest('browser/listings.json', ''));

This means java home path is different on all applications. If we run a second application, it will receive all java standard classes again. Can be set a centralized path? I believe /sys is also used for application class files and jars. May be another mount point will be necessary?

Thanks

**Comment by bertung** [comment]
Some thing like this with a absolute path?

mfs.mount('/java', new BrowserFS.FileSystem.XmlHttpRequest('/javahome/listings.json', ''));

**Comment by jvilk** [comment]
When you construct a JVM instance, you explicitly tell DoppoJVM where Doppio's home is, which is separate from the classpath you give it. The application class files can be anywhere in the filesystem; you just have to make sure they are on the classpath you give DoppioJVM.

It's the same as the JVM you run natively when you run `java` on the command line.

Does that help? I'm a bit confused about your question.

**Comment by bertung** [comment]
To be clear, for example, will String.class be cached to the browser, and will that cached String.class be available to all applications running from separate absolute paths?

**Comment by jvilk** [comment]
Assuming you're using the `master` version of DoppioJVM, which has a JAR-based Java Class Library:

`String.class` is a file stored within `rt.jar`. If you're using the `XmlHttpRequest` file system for Doppio's home, BrowserFS will cache `rt.jar` in-memory until the page reloads. Thus, subsequent JVM invocations will not re-download `rt.jar`.

In this setup, the browser should also cache `rt.jar`, so re-visits to the webpage should be able to avoid re-downloading the file.

You will only circumvent BrowserFS's caching if you mount Doppio's home in multiple locations in the file system using *different XmlHttpRequest file systems*. If you do that, BrowserFS will have a separate cache for each `XmlHttpRequest` file system, leading to inflated memory usage as your JVMs pull in multiple copies of the Java Class Library.

The best way to configure DoppioJVM for a multi-app setup is to have a single location for Doppio's home, e.g. `/sys`, and mounting the applications -- without Doppio's files -- to separate locations. You can generate `listings.json` for an arbitrary folder using a CoffeeScript script in BrowserFS:

https://github.com/jvilk/BrowserFS/blob/master/tools/XHRIndexer.coffee

Usage: From within the directory you want to index: `/path/to/tools/XHRIndexer.coffee > listings.json`

Does that answer your question?

**Comment by bertung** [comment]
Yes, thank you very much. I am almost done with our doppioJVM support. I will start running applications built for our distributed operating system probably next week. I would have more questions in the process.

**Comment by jvilk** [comment]
Great! I'll close this out as answered.
