### ISSUE TITLE
Question: why a difference between invokestatic_fast and invokevirtual_fast when computing paramWordSize?

### ISSUE THREAD

**Issue by hrj** [plasma-umass/doppio#438]
While looking through the code I noticed a difference between two opcode implementations:

`invokestatic_fast` uses `methodReference.paramWordSize` directly, while `invokevirtual_fast` uses `methodReference.getParamWordSize()`

Is it a deliberate choice or an oversight?

**Comment by jvilk** [comment]
Hmm... this may be an oversight.

I definitely know there is at least one case where `getParamWordSize` is needed and is called when the `methodReference` is not resolved, but that may be in a reflection method.

You could do a test and see if `paramWordSize` is ever `-1` during an `invokevirtual_fast`.
