### ISSUE TITLE
Question: How to setup networking with doppio in browser?

### ISSUE THREAD

**Issue by hrj** [plasma-umass/doppio#442]
I have read through this [wiki page](https://github.com/plasma-umass/doppio/wiki/Networking-with-Doppio) and through `src/natives/java_net.ts`, but I am not fully certain how this works.

The image on the wiki page is not loading, which may have held some clues.

If I understand right, whenever a socket connection to `host:port` is requested from Java land, that gets converted to a `ws://host:port` request. Hence, if I need to connect to `xyz.com:80` via `HttpURLConnection`, I will need to first run a websocket server (websockify) on `xyz.com:80`.

Alternatively, I could run websockify on my own host and configure the http proxy in Java Land to point to this, so that all http requests get routed to my host, and then proxied to the final destination.

Is the above right?

Thanks!

**Comment by jvilk** [comment]
> If I understand right, whenever a socket connection to host:port is requested from Java land, that gets converted to a ws://host:port request. Hence, if I need to connect to xyz.com:80 via HttpURLConnection, I will need to first run a websocket server (websockify) on xyz.com:80.

Yup, you got it right.

> Alternatively, I could run websockify on my own host and configure the http proxy in Java Land to point to this, so that all http requests get routed to my host, and then proxied to the final destination.

We haven't implemented it that way, but yes, this is possible.

The current networking code needs to be tested/cleaned up/updated to use the latest websockify. I admit that I have let it languish for the past couple of years, mainly because I never set up automated testing with websockify. Once we have automated tests that fail, it should not be too difficult to fix the implementation.

**Comment by hrj** [comment]
Thanks for the detailed response, as always! :+1:

**Comment by jvilk** [comment]
[Here are actual instructions from our 2014 demo](https://github.com/plasma-umass/doppio-demo/blob/c7f4a8a28684740b6d3036722145d249353c52a7/index.md#mess-around-with-sockets). That's how it is supposed to work.
