### ISSUE TITLE
Will Java 7 or 8 be supported in the future?

### ISSUE THREAD

**Issue by karussell** [plasma-umass/doppio#445]
Are they any plans for more recent Java versions?

**Comment by jvilk** [comment]
Doppio supports Java 7 and 8, but our demo is unfortunately quite outdated, and I have not had time to put a new one together.

Do we have outdated documentation somewhere?

**Comment by karussell** [comment]
On the demo page it says: 'Please note that DoppioJVM is Java 6 compatible; Java 7 programs will not function on DoppioJVM.'

http://plasma-umass.github.io/doppio-demo/

**Comment by ianopolous** [comment]
+1 to updating the demo. I'd love to try JPC in it!

**Comment by jvilk** [comment]
A new demo has emerged!

https://plasma-umass.github.io/doppio-demo/

It has all of the good stuff we've been working hard on for the past two years.
