### ISSUE TITLE
Use Array/Uint8Array for `code` instead of `Buffer`

### ISSUE THREAD

**Issue by jvilk** [plasma-umass/doppio#450]
BrowserFS's `Buffer` imposes expensive abstraction overhead. I initially used it because older versions of IE did not support TypedArrays, but those versions are not commonly used anymore.

We should switch to using `Uint8Array` (and an `Array` of numbers in non-typed-array browsers) to make the interpreter faster. The method can also contain a `DataView` view of the buffer for the rare opcodes that need to read 16 or 32-bit numbers.

**Comment by nybbs2003** [comment]
+1

**Comment by jvilk** [comment]
The latest release uses the [NPM buffer package](https://github.com/feross/buffer), which implements `Buffer` atop `Uint8Array` objects.
