### ISSUE TITLE
"node ./prepublish.js" failure

### ISSUE THREAD

**Issue by ashishtara** [plasma-umass/doppio#460]
The npm install step for building doppio fails on my Win 7 system (log attached) in the prepublish step.

[npm-debug.log.txt](https://github.com/plasma-umass/doppio/files/292908/npm-debug.log.txt)

**Comment by jvilk** [comment]
Thanks for the report!

**Comment by ashishtara** [comment]
Thanks for the quick fix, it's working now:)
