### ISSUE TITLE
Run without webserver

### ISSUE THREAD

**Issue by Dexdev08** [plasma-umass/doppio#464]
Can you run doppio offline with just pure js payload? (Or locally loaded files?)

**Comment by jimfb** [comment]
@Dexdev08 Yes.  Doppio does NOT require server-side support.

**Comment by jvilk** [comment]
Yes, this should work. The webserver only serves up files via HTTP and does nothing more. If `XMLHttpRequest` works over a `file://` URL, then the example code should just work.
