### ISSUE TITLE
Clojure does not work (wrong filename)

### ISSUE THREAD

**Issue by noncom** [plasma-umass/doppio#465]
Hi!

In the demo I tried the `clojure` command and it downloaded `clojure-1.7.0.jar` in `/home/programs`, but to actually run Clojure, it looks for `clojure1.7.0.jar` and fails to find it. I tried to `cp clojure-1.7.0.jar clojure1.7.0.jar` but got a `EPERM`. Could you please fix things for Clojure? :)

**Comment by jvilk** [comment]
Ah! You're right. You can manually run it with `java -jar /path/to/clojure.jar` to get around it for now until I update the demo.

**Comment by jvilk** [comment]
Fixed!
