### ISSUE TITLE
Could the thread.throwNewException() method use thread.getLoader() instead of thread.getBsCl()

### ISSUE THREAD

**Issue by hrj** [plasma-umass/doppio#468]
The `thread.throwNewException()` method is very convenient when throwing exceptions from native code. However, it uses the bootstrap class loader for loading the exception class, making it difficult to throw custom exceptions.

If it uses the loader from `getLoader()`, user defined exceptions can be easily thrown.

**Comment by jvilk** [comment]
Sounds good to me. Feel free to open a PR!
