### ISSUE TITLE
TypeScript doesn't build

### ISSUE THREAD

**Issue by PaulBGD** [plasma-umass/doppio#489]
Looks like it's due to: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12942

**Comment by PaulBGD** [comment]
Oh another issue with the build is that the tasks use an array of AsyncFunctions, which now require 2 generics:
```
tasks/includes.ts(15,33): error TS2314: Generic type 'AsyncFunction<T, E>' requires 2 type argument(s).
tasks/java.ts(50,22): error TS2314: Generic type 'AsyncFunction<T, E>' requires 2 type argument(s).
tasks/unit_test.ts(9,20): error TS2314: Generic type 'AsyncFunction<T, E>' requires 2 type argument(s).
```

**Comment by PaulBGD** [comment]
Looks like a quick fix for both of these issues is to change the typings version for `async: https://github.com/jvilk/BrowserFS/issues/165#issuecomment-263137208

**Comment by PaulBGD** [comment]
Found one more issue why it doesn't build: #491

**Comment by jvilk** [comment]
@PaulBGD is this fixed with your PR? Seems like it is, since the builds are green.

**Comment by PaulBGD** [comment]
Yep! Thanks for pulling.
