### ISSUE TITLE
Compile to WebAssembly

### ISSUE THREAD

**Issue by ExE-Boss** [plasma-umass/doppio#496]
Because WebAssembly is a lot faster than JavaScript, and TypeScript is typed it would be better to compile the TypeScript code to something closer to machine code.

There are already experimental utilities that allow compiling TypeScript code to WebAssembly: https://github.com/rsms/wasm-util

**Comment by jvilk** [comment]
@ExE-Boss Those tools let you work with WebAssembly code from TypeScript; it doesn't compile TypeScript to WebAssembly.

Like with ASM.js, porting Doppio's JVM to use WebAssembly would require us to implement a complete garbage collector in JavaScript, implement an FFI between JavaScript and DoppioJVM, and many other changes. It is beyond the scope of the project.

**Comment by ExE-Boss** [comment]
**Update:** [**AssemblyScript**](https://github.com/AssemblyScript/assemblyscript) [<img align="top" alt="(on&nbsp;npm)" src="https://img.shields.io/npm/v/assemblyscript.svg"/>](https://www.npmjs.com/package/assemblyscript "The version on npm is out of date due to the W.I.P. nature of the project") plans to be a 1:1 TypeScript to WASM compiler ([see&nbsp;Status&nbsp;and&nbsp;Roadmap](https://github.com/AssemblyScript/assemblyscript/wiki/Status-and-Roadmap)).
