### ISSUE TITLE
how about implement Graphic APIs via canvas and WebGL?

### ISSUE THREAD

**Issue by yunfan** [plasma-umass/doppio#501]
how about implement Graphic APIs via canvas and WebGL?

**Comment by jvilk** [comment]
I don't know what graphics API you are referring to. If you mean JavaFX, there's [an issue about that](https://github.com/plasma-umass/doppio/issues/373). If you mean AWT/Swing, there's a [issue/comment describing why this is hard](https://github.com/plasma-umass/doppio/issues/45). If you mean jogl / webgl, I recently received an email from someone interested in working on that.

I personally do not have time to implement one of these graphics APIs, but I welcome pull requests and proposals on how to do so.

**Comment by yunfan** [comment]
yes i mean jogl/webgl, can you point me the link that guys's project?
