### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Native method 'sun.ma nagement.OperatingSystemImpl.initialize()V' not implemented.

### ISSUE THREAD

**Issue by james-pre** [plasma-umass/doppio#541]
Reproduction:

- Download server.jar from https://mcversions.net/download/1.8
- Start Doppio and upload server.jar
- Run `java -jar server.jar`
- Error

Yes, I was trying to run a Minecraft server. I don't know any Java so I'm not entirely sure what needs to be fixed.

**Comment by emeryberger** [comment]
I don't think this will ever be possible to support a server like this in Doppio or in any in-browser environment because of the browser's security restrictions.
