### ISSUE TITLE
How is it working?

### ISSUE THREAD

**Issue by cemalgnlts** [plasma-umass/doppio#543]
Hi,

The project is really interesting. I wanted to learn how it works but didn't know where to start. How does the Java code work? I guess it's not using something like an emulator or wasm. It seems there are only JS codes.

**Comment by emeryberger** [comment]
This paper has an overview of how it works.

https://people.cs.umass.edu/~emery/pubs/Doppio-Vilk-Berger-PLDI2014.pdf

**Comment by cemalgnlts** [comment]
Thanks.
