### ISSUE TITLE
Better Interface for Adding In-Browser Terminal Commands

### ISSUE THREAD

**Issue by jvilk** [plasma-umass/doppio#76]
Currently, in order to add a terminal command to the browser, you need to:

* Create a function with the name of the command in the `commands` hash.
* Add code for processing / checking arguments.
* If you want tab completion, add custom code to the `fileNameCompletions` method that checks for your command.
* Add relevant text to the ``help`` command.

As a result, it's somewhat frustrating to add new commands, as you need to touch a bunch of code in `frontend.coffee`. And I currently wish to add a bunch of new commands due to our new in-browser filesystem (Doppio shell scripts anyone?).

Here's how I believe terminal commands should work:
* On load, each command 'registers' itself with the terminal with the following information:
  * The command's name.
  * A string with the command's syntax (e.g. for ``cd``, ``<dir>``).
  * A string with a quick sentence describing the command (e.g. ``Changes the current directory.``)
  * A function that implements the command, which takes in an object with arguments.
  * [Optional] A "command group" that the command should belong to (will be used for ``help`` output).
  * [Optional] A function that takes in a partially entered command that returns the appropriate tab-completion handler to use (will default to something that just autocompletes arbitrary filenames). 99% of the use cases can be handled with handlers that only return files of a particular file extension.

When a command is entered, the arguments are run through ``optimist`` before being passed to the command handler (which can probably run in the browser, thanks to our fake Node API).

This structure should also be able to handle meta commands, like ``time`` and ``help``.

Thoughts...?

**Comment by perimosocordiae** [comment]
This should be handled by doppio-demo now. Closing.
